spring:
  application:
    name: TestApplication
  cloud: 
    config:
      uri: http://localhost:8888
      enabled: true

server:
  port: 8086

management:
  endpoints:
    web:
      exposure:
        include: '*'

hello:
  rel: bsjghdajsh
